### ISSUE TITLE
how to train on my own data

### ISSUE THREAD

**Issue by wlsonia** [yangyanli/PointCNN#178]
how to train on my own data,just have a txt file    x,y,z

**Comment by burui11087** [comment]
Hi @wlsonia 

Please refer to this [file](https://github.com/yangyanli/PointCNN/blob/master/data_conversions/prepare_scannet_cls_data.py) and convert you txt file to h5 file. xyz is enough and RGB information is not necessary.

Thanks.

**Comment by wlsonia** [comment]
谢谢






At 2019-07-23 13:09:48, "Rui Bu" <notifications@github.com> wrote:


Hi @wlsonia

Please refer to this file and convert you txt file to h5 file. xyz is enough and RGB information is not necessary.

Thanks.

**Comment by wlsonia** [comment]
thanks,I want to label my point cloud,can you recommend me an annotation software?thank you.

**Comment by spiegelss** [comment]
[Cloud Compare](https://www.danielgm.net/cc/) have some segmentation algorithms that may make annotating easier.  What I've also done is projected my point cloud to 2D space and then used image segmentation techniques to make that sort of thing easier (especially if it's an aerial collect).  [Skimage](https://scikit-image.org/docs/dev/api/skimage.html) has quite a few image segmentation routines that might make things easier for you.

**Comment by spiegelss** [comment]
Also one thing I do is start with ground segmentation.  that may make segmentation easier because you have the ground out of the way.  @burui11087 would you be able to do a binary classification with PointCNN (ground vs non ground)?  That might be a way to get used to deep learning with PointCNN.  That's one thing I was considering trying with my data to get started and then going from there.  [CSF](https://github.com/jianboqi/CSF) is a pretty straight forward way of segmenting the ground returns.

**Comment by HuiminYang** [comment]
Have you successfully trained your dataset?

**Comment by HuiminYang** [comment]
I have debugged the original author's modelnet classification network code, generated my own h5 file, changed the number of categories to my own category number, and changed the dataset path to my own dataset path. However, the program run incorrectly., I don't know why, I feel that there are some changes, I didn't find it, If you have successfully trained your dataset, I hope you can give me some advice.

**Comment by sanghyunbai** [comment]
Hi, I have pts data prepared, I wish to understand exact part of code that I have to change. Please consult.

**Comment by SERPENT-H** [comment]
Hi
I have  txt files that contain x,y,z,r,g,b,i information,but when I run the prepare_sannet_data_cls.py file,an error occurred and I don't know how to solve it .
**Traceback (most recent call last):
  File "prepare_scannet_cls_data.py", line 75, in <module>
    main()
  File "prepare_scannet_cls_data.py", line 54, in main
    indices = np.random.choice(pt_num, sample_num, replace=(pt_num < sample_num))
  File "mtrand.pyx", line 894, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
**
I think it is points number < sample number,but points in my txt file are more than 3 million,so I have no idea what to do next
