### ISSUE TITLE
Unable to compile the sample file in python3

### ISSUE THREAD

**Issue by aniqueakhtar** [yangyanli/PointCNN#55]
I have in the past able to successfully compile the sampling file using python2 for PointNet++.

However, I am unable to compile it and use it with PointCNN.

This is the bash file:

`#/bin/bash
PYTHON=python3
CUDA_PATH=/usr/local/cuda
TF_LIB=$($PYTHON -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
TF_PATH=$(python3 -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
$CUDA_PATH/bin/nvcc tf_sampling_g.cu -o tf_sampling_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
g++ -std=c++11 tf_sampling.cpp tf_sampling_g.cu.o -o tf_sampling_so.so -shared -fPIC -L$TF_LIB -ltensorflow_framework -I $TF_PATH/external/nsync/public/ -I $TF_PATH -I $CUDA_PATH/include -lcudart -L $CUDA_PATH/lib64/ -O2 -D_GLIBCXX_USE_CXX11_ABI=0`

where the two commands give this output in the terminal

`$($PYTHON -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
-bash: /home/aakhtar/.conda/envs/anique2/lib/python3.6/site-packages/tensorflow: Is a directory`
and
`$(python3 -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
-bash: /home/aakhtar/.conda/envs/anique2/lib/python3.6/site-packages/tensorflow/include: Is a directory`

so I know both these commands are working. The cuda folder is correct too.  When I compile this, it gives no errors.
 
However, when I run the train_val_seg.py file, I get the following error:

`Traceback (most recent call last):
  File "../train_val_seg.py", line 268, in <module>
    main()
  File "../train_val_seg.py", line 119, in main
    net = model.Net(points_augmented, features_augmented, is_training, setting)
  File "/home/aakhtar/PointCNN_v1/pointcnn_seg.py", line 12, in __init__
    PointCNN.__init__(self, points, features, is_training, setting)
  File "/home/aakhtar/PointCNN_v1/pointcnn.py", line 64, in __init__
    from sampling import tf_sampling
  File "/home/aakhtar/PointCNN_v1/sampling/tf_sampling.py", line 15, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/home/aakhtar/.conda/envs/anique2/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/aakhtar/.conda/envs/anique2/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/aakhtar/PointCNN_v1/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`

I am assuming, this error arises from the fact that the sampling file has not been compiled properly.
I am using a Conda environment.
outside the Conda environment, I have got python 3.4.8, and Tensorflow 1.6.0
however, inside the environment, I am using 3.6.6, and Tensorflow 1.6.0
The Cuda link is from outside the environment.

Can you please help me understand as to what is going wrong.
Thanks.

**Comment by aniqueakhtar** [comment]
So what I did was, I uninstalled anaconda altogether and started on a virtual environment from python.

I ended up receiving the following error in the same file again:

`ARNING:tensorflow:From /home/aakhtar/PointCNN/PointCNN_v1/pointfly.py:123: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-07-30 18:53:52.465943: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/client/session.py", line 1332, in _run_fn
    self._extend_graph()
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/client/session.py", line 1392, in _extend_graph
    graph_def.SerializeToString(), status)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

         [[Node: FarthestPointSample = FarthestPointSample[npoint=768](add)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../train_val_seg.py", line 270, in <module>
    main()
  File "../train_val_seg.py", line 184, in main
    sess.run(init_op)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

         [[Node: FarthestPointSample = FarthestPointSample[npoint=768](add)]]

Caused by op 'FarthestPointSample', defined at:
  File "../train_val_seg.py", line 270, in <module>
    main()
  File "../train_val_seg.py", line 117, in main
    net = model.Net(points_augmented, features_augmented, is_training, setting)
  File "/home/aakhtar/PointCNN/PointCNN_v1/pointcnn_seg.py", line 12, in __init__
    PointCNN.__init__(self, points, features, is_training, setting)
  File "/home/aakhtar/PointCNN/PointCNN_v1/pointcnn.py", line 93, in __init__
    fps_indices = tf_sampling.farthest_point_sample(P, pts)
  File "/home/aakhtar/PointCNN/PointCNN_v1/sampling/tf_sampling.py", line 59, in farthest_point_sample
    return sampling_module.farthest_point_sample(inp, npoint)
  File "<string>", line 49, in farthest_point_sample
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/aakhtar/virtual1/lib64/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

         [[Node: FarthestPointSample = FarthestPointSample[npoint=768](add)]]`

**Comment by burui11087** [comment]
Hi @aniqueakhtar 

I tried to replicate your issue, but I didn't occur it. I recommend you use docker directly or replace Conda environment python 3.6.6 with python 3.5.X.

Thanks!!

**Comment by aniqueakhtar** [comment]
Got this working with a docker image, as well as python's virtual environment.

I believe with conda, somehow while compiling the file, Cuda was using the tensorflow from outside the conda virtual environment. and therefore creating discrepancies.
