### ISSUE TITLE
abount the segmentation of semantic3d

### ISSUE THREAD

**Issue by YukioSama** [yangyanli/PointCNN#75]
during running the code about segmentating the semantic3d dataset,following problem comes up,i can you tell what is the reason and how to resolve?
`2018-09-22 12:27:32.108646-Loading ../../data/semantic3d/train/sg28_station4_intensity_rgb.txt...
Traceback (most recent call last):
  File "prepare_semantic3d_data.py", line 241, in <module>
    main()
  File "prepare_semantic3d_data.py", line 50, in main
    xyzirgb = np.loadtxt(filename_txt)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 1092, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 1016, in read_data
    % line_num)
ValueError: Wrong number of columns at line 75685977`

**Comment by burui11087** [comment]
Hi @YukioSama 

This error is caused by semantic3d self's issue, you need to modify it handly.

Thanks

**Comment by burui11087** [comment]
you can open "sg28_station4_intensity_rgb.txt" by sublime or something else, you will find this error.
